select * from customer limit 20
--what is the total revenue generated by male and female
select gender ,SUM(purchase_amount) as revenue
from customer
group by gender

--which customer used discount but still spend more then avg amount 
select customer_id , purchase_amount from customer 
where discount_applied ='Yes' and 
purchase_amount>= (select AVG(purchase_amount) from customer)

--what are the 5 top products from the avg review rating 
select item_purchased ,ROUND(AVG(review_rating::numeric),2) 
as "Average" from customer group by item_purchased 
order by avg(review_rating)desc limit 5 ;

--comapre the average purchase amt between standard and express shipping
select shipping_type , ROUND(avg(purchase_amount),2) from customer
where shipping_type in('Standard' , 'Express')
group by shipping_type

--do suscribed customers spend more? 
--and compare avg spend and total revenue between suscribers and non-suscriber
select subscription_status , count(customer_id) as total_customer,
ROUND(avg(purchase_amount),2) as avg_spend , 
ROUND(sum(purchase_amount),2) as total_spend from 
customer group by subscription_status 
order by total_spend , avg_spend desc

--which top 5 products have the highest percentage of purchase with discount
select item_purchased,
ROUND(100 * sum(CASE when discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased 
order by discount_rate desc limit 5;

--segment customer into new, returning and loyal based on thier total 
--number of pervious purchase , and show count of each segment
with customer_type as(
select customer_id , previous_purchases,
CASE 
  when previous_purchases = 1 THEN 'New'
  when previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
  ELSE 'Loyal'
  END as customer_segment
  from customer
)
select customer_segment , count(*) as "number of customers"
from customer_type group by customer_segment

-- what are the top 3 products within each catogry
--advanced query
with item_counts as (
select category,item_purchased ,
count (customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank,item_purchased , total_orders from item_counts
where item_rank<=3;


--are customers who are the repeated buyers are actually susbcribe?(previous purchase more than 5)
select subscription_status , count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--what is the revenue contribution of each diff age group
select age_group , sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;